---
title: "Spatial_Assignment_3"
author: "Group22: Jeb Polstein, Matt Khinda, Yoji Toriumi"
date: "9/16/2021"
output: html_document
---

```{r, result = FALSE}
library(sf)
library(tigris)
library(tidyverse)
library(zonebuilder)
library(ggthemes)
library(ggspatial)
library(units)
library(nngeo)
```

## Extracted some data from [Analyze Boston](https://data.boston.gov/)

```{r, message=FALSE, results = FALSE}
hospitals <- read_sf("https://bostonopendata-boston.opendata.arcgis.com/datasets/8f1e5741a4ee4c0f82925d17aab3c002_2.kml?outSR=%7B%22latestWkid%22%3A2249%2C%22wkid%22%3A102686%7D")
universities <- read_sf("https://bostonopendata-boston.opendata.arcgis.com/datasets/cbf14bb032ef4bd38e20429f71acb61a_2.kml?outSR=%7B%22latestWkid%22%3A2249%2C%22wkid%22%3A102686%7D")
policest <- read_sf("https://bostonopendata-boston.opendata.arcgis.com/datasets/e5a0066d38ac4e2abbc7918197a4f6af_6.kml?outSR=%7B%22latestWkid%22%3A2249%2C%22wkid%22%3A102686%7D")
openspace <- read_sf("https://bostonopendata-boston.opendata.arcgis.com/datasets/2868d370c55d4d458d4ae2224ef8cddd_7.kml")
bikenet <- read_sf("https://bostonopendata-boston.opendata.arcgis.com/datasets/1f63e8e31f664833827c407c021ad60c_0.kml?outSR=%7B%22latestWkid%22%3A2249%2C%22wkid%22%3A102686%7D")
neighbor <- read_sf("https://bostonopendata-boston.opendata.arcgis.com/datasets/3525b0ee6e6b427f9aab5d0a1d0a1a28_0.kml?outSR=%7B%22latestWkid%22%3A2249%2C%22wkid%22%3A102686%7D")
hydro <- read_sf("https://bostonopendata-boston.opendata.arcgis.com/datasets/2b3c0fa13b1c468eb702a3645fcc6bcb_5.kml")
tracts <- tracts(state = "MA", county = "Suffolk")
boundary <- st_read("https://bostonopendata-boston.opendata.arcgis.com/datasets/142500a77e2a4dbeb94a86f7e0b568bc_9.geojson?outSR=%7B%22latestWkid%22%3A2249%2C%22wkid%22%3A102686%7D")
```

```{r, message=FALSE}
MA_state_plane <- "+proj=lcc +lat_1=41.71666666666667 +lat_2=42.68333333333333 +lat_0=41 +lon_0=-71.5 +x_0=200000 +y_0=750000 +ellps=GRS80 +units=m +no_defs"
hospitals <- hospitals %>% 
  st_transform(2249)
universities <- universities %>% 
  st_transform(2249)
policest <- policest %>% 
  st_transform(2249)
openspace <- openspace %>% 
  st_transform(2249)
bikenet <- bikenet %>% 
  st_transform(2249)
neighbor <- neighbor %>% 
  st_transform(2249)
hydro <- hydro %>% 
  st_transform(2249)
tracts <- tracts %>% 
  st_transform(2249)
boundary <- boundary %>% 
  st_transform(2249)
tracts <- tracts[boundary, ]
grid <- st_sf(st_make_grid(boundary, n = c(20, 20)))
grid <- grid[boundary, ]
clock <- zb_zone("Boston", distance = 0.5, distance_growth = 0, n_circles = 20)
clock <- clock %>% st_transform(2249)
clock <- clock[boundary, ]
boundary <- boundary %>% st_transform(2249)
```

## Some data are shown as follows
```{r, message=FALSE}
ggplot(neighbor) +
  geom_sf() +
  geom_sf(data = hospitals, color = "red") +
  geom_sf(data = universities, color = "orange") +
  geom_sf(data = policest, color = "green") +
  geom_sf(data = bikenet) +
  geom_sf(data = openspace) +
  geom_sf(data = hydro, fill = "blue") +
  theme_classic() +
  annotation_scale()
```

```{r, message=FALSE}
openspace_buffer <- st_buffer(openspace, dist = 100) %>% 
  st_union()

ggplot(openspace_buffer) +
  geom_sf() +
  theme_map()
```
```{r, message=FALSE}
hospitals_openspace <- hospitals[openspace_buffer, ]

ggplot(openspace_buffer) +
  geom_sf() +
    geom_sf(data = hospitals_openspace,
          color = "tomato",
          size = 0.5) +
  theme_map()
```

```{r, message=FALSE}
hospitals <- hospitals %>% 
  st_join(hospitals_openspace) %>% 
  mutate(by_openspace = !is.na(Name.y))
```

## how many hospitals are within 100m of openspaces
```{r, message=FALSE}
n_openspace_hospitals <- sum(hospitals$by_openspace)

n_openspace_hospitals
```
## ratio
```{r, message=FALSE}
n_hospitals <- length(hospitals$by_openspace)

pct_openspace_hospitals <- n_openspace_hospitals / n_hospitals * 100

pct_openspace_hospitals
```

```{r, message=FALSE}
left_side <- st_bbox(hospitals)$xmin
top_side  <- st_bbox(hospitals)$ymax

ggplot(hydro) +
  geom_sf(fill = "cadetblue1", color = NA) +
  geom_sf(data = hospitals, size = 3,
          aes(color = by_openspace)) +
  scale_color_manual(values = c("chartreuse1", "tomato"),
                     name = "Boston Hospitals\nby distance to openspace",
                     labels = c("No openspace within 100m",
                                "Openspace within 100m")) +
  annotation_scale(location = "br") +
  annotation_north_arrow(location = "tr",
                         style = north_arrow_minimal()) +
  annotate(geom =  "text", x = left_side,
           y = top_side,
           label = paste("Of the ", 
                         prettyNum(n_hospitals),
                         " hospitals in Boston\n", 
                         prettyNum(n_openspace_hospitals),
                         " (", 
                         prettyNum(pct_openspace_hospitals, digits = 0),
                         "%) are within 100\nmeters of openspace.",
                         sep = ""),
           hjust = 0, vjust = 0, size = 3) +
  theme_map() +
    theme(panel.background = element_rect(fill = "antiquewhite"),
        legend.background = element_rect(fill = alpha("white", 0.5), 
                                         color = "gray"))
```

```{r, message=FALSE}
neighbor <- neighbor %>% 
  mutate(num_police = lengths(st_covers(neighbor, policest)))

ggplot(neighbor) +
  geom_sf(color = NA,
          aes(fill = num_police)) +
  scale_fill_viridis_c(name = "Boston neighborhoods\nbynumber of police station",
                       breaks = breaks <- seq(0, 2, by = 1),
                       labels = paste(prettyNum(breaks),
                                      "police stations")) +
  annotation_scale(location = "br") +
  annotation_north_arrow(location = "tr",
                         style = north_arrow_minimal()) +
  theme_map() +
  theme(legend.background = element_rect(fill = alpha("white", 0.5), 
                                         color = "gray"))


```

```{r, message=FALSE}
neighbor <- neighbor %>%
  mutate(area = set_units(st_area(neighbor), km^2)) %>%
  mutate(police_dens = as.numeric(num_police/ area))

ggplot(neighbor) +
  geom_sf(color = NA,
          aes(fill = police_dens)) +
  scale_fill_viridis_c(name =
                         "Boston neighborhoods \nby police station density",
                       breaks = breaks <- seq(0, 0.62, by = 0.1),
                       labels = paste(prettyNum(breaks),
                                      "police stations per sq km")) +
  annotation_scale(location = "br") +
  annotation_north_arrow(location = "tr",
                         style = north_arrow_minimal()) +
  theme_map() +
  theme(legend.position = "right",
         legend.background = element_rect(fill = alpha("white", 0.5), 
                                         color = "gray"))
```

```{r, results = FALSE}
openspace <- openspace %>% 
  mutate(hospitals_dist = st_nn(openspace, hospitals,
                                returnDist = TRUE)$dist) %>% 
  mutate(hospitals_dist = as.numeric(hospitals_dist))
```

```{r, message=FALSE}
avg_hospitals_dist <- mean(openspace$hospitals_dist)

avg_hospitals_dist
```
```{r, message=FALSE}
right_side <- st_bbox(openspace)$xmax
left_side  <- st_bbox(openspace)$xmin
top_side <- st_bbox(openspace)$ymax
bottom_side <- st_bbox(openspace)$ymin

ggplot(hydro) +
  geom_sf(fill = "cadetblue1", color = NA) +
  geom_sf(data = openspace, aes(fill = hospitals_dist)) +
  coord_sf(xlim = c(left_side, right_side),
           ylim = c(bottom_side, top_side), expand = FALSE) +
  scale_fill_viridis_c(name = "Boston Openspace \nby distance to a hospital") +
  annotation_scale(location = "br") +
  annotation_north_arrow(location = "tr",
                         style = north_arrow_nautical()) +
  annotate(geom = "text", x = left_side + 300,
           y = top_side - 500,
           label = paste("On average, a Boston openspace\nis ",
                         prettyNum(avg_hospitals_dist, digits = 3),
                         "m",
                         sep = ""),
           hjust = 0, size = 3) +
  theme_map() +
  theme(panel.background = element_rect(fill = "antiquewhite"),
        legend.background = element_rect(fill = alpha("white", 0.5), 
                                         color = "gray"))
```

##Identifying Overlapping Polygons
```{r, message=FALSE}
neighbor <- neighbor %>%
  mutate(num_hospitals = lengths(st_covers(neighbor, hospitals))) %>% 
  mutate(has_hospitals = num_hospitals > 0)

n_hospitals_neighbor <- sum(neighbor$has_hospitals)

n_hospitals_neighbor
```

```{r, message=FALSE}
left_side  <- st_bbox(neighbor)$xmin
top_side <- st_bbox(neighbor)$ymax

ggplot(hydro) +
  geom_sf(fill = "cadetblue1", color = NA) +
  geom_sf(data = neighbor,
          aes(fill = has_hospitals)) +
  scale_fill_manual(values = c("chartreuse1", "tomato"),
                    name = "Boston Neighborhoods\nby presence of a hospital",
                    labels = c("Neighborhood without\nany presence of a hospital",
                               "Neighborhood with \n presence of a hospital(s)")) +
  annotation_scale(location = "br") +
  annotation_north_arrow(location = "tr",
                         style = north_arrow_minimal()) +
  annotate(geom = "text", x = left_side, 
           y = top_side - 1000, 
           label = paste(n_hospitals_neighbor,
                         "of Boston's",
                         length(neighbor$Name),
                         "neighborhoods contain a hospital(s)."),
           hjust = 0, vjust = -5, size = 3) +
  theme_map() +
  theme(panel.background = element_rect(fill = "antiquewhite"),
        legend.background = element_rect(fill = alpha("white", 0.5), 
                                         color = "gray"))

```

```{r, message=FALSE}
grid <- grid %>%
  mutate(num_hospitals = lengths(st_covers(grid, hospitals))) %>% 
  mutate(area = set_units(st_area(grid), km^2)) %>% 
  mutate(hospitals_dens = as.numeric(num_hospitals / area))


plot_5 <- ggplot(grid) +
  annotation_map_tile(zoomin = 0, progress = "none", type = "cartolight") +
  geom_sf(data = grid, alpha = 1/2, aes(fill = hospitals_dens)) +
  scale_fill_viridis_c(name = "Schools per square km") +
  labs(caption = "Map tiles and data by OpenStreetMap") +
  theme_void()

plot_5
```

```{r, message=FALSE}
clock <- clock %>%
  mutate(num_hospitals = lengths(st_covers(clock, hospitals))) %>% 
  mutate(area = set_units(st_area(clock), km^2)) %>% 
  mutate(hospitals_dens = as.numeric(num_hospitals / area))

plot_7 <- ggplot(clock) +
  annotation_map_tile(zoomin = 0, progress = "none", type = "cartolight") +
  geom_sf(alpha = 1/2, aes(fill = hospitals_dens)) +
  scale_fill_viridis_c(name = "Hospitals per square km") +
  labs(caption = "Map tiles and data by OpenStreetMap") +
  theme_void()

plot_7
```

```{r, echo=FALSE}

```

```{r, echo=FALSE}

```

```{r, echo=FALSE}

```

```{r, echo=FALSE}

```

```{r, echo=FALSE}

```

```{r, echo=FALSE}

```










